version: '3'

services:
  mysql:
    build:
      context: docker/mysql
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - .docker/mysql/log:/var/log/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - UPLOAD_LIMIT=500M
    depends_on:
      - mysql

  php:
    build:
      context: docker/php
    depends_on:
      - mysql
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
      - DATABASE_URL=mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@mysql:3306/${DATABASE_NAME}?serverVersion=5.7
    volumes:
      - .:/var/www
#    command: php bin/console messenger:consume pre_order_recalculate

  nginx:
    build:
      context: docker/nginx
    volumes:
      - .:/var/www
      - .docker/nginx/logs/:/var/log/nginx
    depends_on:
      - php
    ports:
      - "80:80"